# Generated by Django 5.2.8 on 2025-11-26 14:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('tara_origine', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('culoare', models.CharField(default='#cccccc', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marime', models.DecimalField(decimal_places=1, max_digits=4)),
                ('greutate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.IntegerField(choices=[(1, 'Aur'), (2, 'Argint'), (3, 'Aur alb'), (4, 'Aur roz')], default=2)),
                ('descriere', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(max_length=15)),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('data_nasterii', models.DateField()),
                ('gen', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilitate', models.BooleanField(default=True)),
                ('data_adaugarii', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='magazin_de_bijuterii.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='magazin_de_bijuterii.categorie')),
                ('dimensiune', models.ManyToManyField(related_name='produse', to='magazin_de_bijuterii.dimensiune')),
                ('material', models.ManyToManyField(related_name='produse', to='magazin_de_bijuterii.material')),
            ],
            options={
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='Imagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagine', models.URLField()),
                ('descriere', models.TextField(blank=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='magazin_de_bijuterii.produs')),
            ],
        ),
        migrations.AddIndex(
            model_name='produs',
            index=models.Index(fields=['pret'], name='magazin_de__pret_b30ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='produs',
            index=models.Index(fields=['disponibilitate'], name='magazin_de__disponi_6c0e1b_idx'),
        ),
    ]
