# Generated by Django 5.2.7 on 2025-10-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_de_bijuterii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('tara_origine', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dimensiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marime', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.IntegerField(choices=[(1, 'Aur'), (2, 'Argint'), (3, 'Aur alb')], default=2)),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilitate', models.BooleanField(default=True)),
                ('data_adaugarii', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_de_bijuterii.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_de_bijuterii.categorie')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_de_bijuterii.material')),
            ],
        ),
        migrations.CreateModel(
            name='Imagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagine', models.URLField()),
                ('descriere', models.TextField()),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_de_bijuterii.produs')),
            ],
        ),
    ]
