# Generated by Django 5.2.8 on 2025-12-06 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_de_bijuterii', '0002_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('subiect', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('data_creare', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_expirare', models.DateField()),
                ('reducere_procent', models.IntegerField(default=10)),
                ('cod_cupon', models.CharField(max_length=50)),
                ('categorii', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(default=django.utils.timezone.now)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_de_bijuterii.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_vizualizare'],
            },
        ),
    ]
