# Generated by Django 5.2.7 on 2025-10-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_de_bijuterii', '0002_brand_categorie_dimensiune_material_produs_imagine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produs',
            old_name='name',
            new_name='nume',
        ),
        migrations.AddField(
            model_name='dimensiune',
            name='greutate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='produs',
            name='dimensiune',
            field=models.ManyToManyField(related_name='produse', to='magazin_de_bijuterii.dimensiune'),
        ),
        migrations.AlterField(
            model_name='dimensiune',
            name='marime',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='imagine',
            name='descriere',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagine',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='magazin_de_bijuterii.produs'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.IntegerField(choices=[(1, 'Aur'), (2, 'Argint'), (3, 'Aur alb'), (4, 'Aur roz')], default=2),
        ),
        migrations.AlterField(
            model_name='produs',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='magazin_de_bijuterii.brand'),
        ),
        migrations.AlterField(
            model_name='produs',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='magazin_de_bijuterii.categorie'),
        ),
        migrations.RemoveField(
            model_name='produs',
            name='material',
        ),
        migrations.AddField(
            model_name='produs',
            name='material',
            field=models.ManyToManyField(related_name='produse', to='magazin_de_bijuterii.material'),
        ),
    ]
