# Generated by Django 5.2.8 on 2025-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_de_bijuterii', '0003_promotie_vizualizare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotie',
            name='categorii',
        ),
        migrations.AddField(
            model_name='promotie',
            name='categorii',
            field=models.ManyToManyField(to='magazin_de_bijuterii.categorie'),
        ),
    ]
