# Generated by Django 5.2.7 on 2025-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_de_bijuterii', '0003_rename_name_produs_nume_dimensiune_greutate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produs',
            options={'ordering': ['nume']},
        ),
        migrations.AddIndex(
            model_name='produs',
            index=models.Index(fields=['pret'], name='magazin_de__pret_b30ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='produs',
            index=models.Index(fields=['disponibilitate'], name='magazin_de__disponi_6c0e1b_idx'),
        ),
    ]
