# Generated by Django 5.2.7 on 2025-10-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_de_bijuterii', '0004_alter_produs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='nume',
        ),
        migrations.AlterField(
            model_name='material',
            name='descriere',
            field=models.TextField(blank=True),
        ),
    ]
