# Generated by Django 5.2.7 on 2025-10-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_de_bijuterii', '0005_remove_material_nume_alter_material_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='culoare',
            field=models.CharField(default='#cccccc', max_length=20),
        ),
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
